title:              Journey with Data
email:             ''
description:      The Deeper You Dive, The Clearer You Will See
author:             Jeremy Kaplan
baseurl:            ""
#url:                "https://jamalkaplan.github.io"

# Social Profiles
twitter_username:   
github_username:    jeremykaplan
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown

paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge
